language: rust

rust:
  - nightly
  - beta
  - stable

before_script:
  - set -e
  # prettier-ignore
  - bash -c -e 'if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      rustup component add rustfmt-preview;
      rustup component add clippy-preview;
      npm install --global prettier;
    fi'

script:
  # prettier-ignore
  - bash -c -e 'if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      prettier --list-different --prose-wrap always "**/*.{md,yml}";
      cargo fmt -- --check;
      cargo clippy -- --deny clippy::all;
    fi'
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - set -e
  - cargo package

deploy:
  provider: releases
  file: target/package/gravatar-${TRAVIS_TAG:1}.crate
  api_key:
    secure: EkxBh9x/MH1uYsQkXvGdMXNcgWeiXss4veq5vtUBqfE1EdTpQWrM9fSwfUdFTprg/PPeRCI/SYa5FgRweD3gydhd4DgKHps4Ar/Ji10jxwc2+43IjCnGF9s7mrbfYC78s8DVxOhuNai6fPqWSFbdtkc4ExmrCcLlp52WMlnah1A=
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: "$TRAVIS_RUST_VERSION = stable"

after_deploy:
  - cargo publish --token "$CRATESIO_TOKEN"

env:
  global:
    - secure: "bDAdWu6YQZ/JBGu6MIqZBAWWTK7v65yabRrR98fyzFrZFUnV6T1G8Yxqvll8zjpaTLKN15NytkCdGywlFe4fDBuTekklCqcnSS2uQlld+IVtxsN6WZsr60JmUDazJUWa7wQGn5pEnqvL1COu0XfD0RlNsM6bzhetsP0lbcJiQaM="
